# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06fad54c09b534ad4957f721896ce8f74afdcbfe9b9879c726fd0cf00106e1533c8ac558dc765ed8950fcc89baecf986bda3757ab0ee21b6d54b63b84cf4455f

test:
  secret_key_base: 33de6a614ef9ca8564783e040df843282354b005337a6138f420781a60702edcdf9c4714128a8c7f93fe5ab897e718770063cfd65d94577aeb56e8c65b3c8464

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
